### ISSUE TITLE
No log output once after session is closed

### ISSUE THREAD

**Issue by takezoe** [wvlet/airframe#1068]
Reproduction code:
```scala
object LogTest extends App with LogSupport {
  Logger.setDefaultFormatter(SourceCodeLogFormatter)
  try {
    newDesign.withSession { s =>
      throw new RuntimeException("test")
    }
  } catch {
    case e: Exception => error(e) // no output
  }
}
```
Output:
```
2020-05-11 20:01:21.235+0900  info [LifeCycleManager] [session:7e07db1f] Starting a new lifecycle ...  - (LifeCycleManager.scala:260)
2020-05-11 20:01:21.265+0900  info [LifeCycleManager] [session:7e07db1f] ======== STARTED ========  - (LifeCycleManager.scala:264)
2020-05-11 20:01:21.266+0900  info [LifeCycleManager] [session:7e07db1f] Stopping the lifecycle ...  - (LifeCycleManager.scala:268)
```

**Comment by xerial** [comment]
The cause is this code https://github.com/wvlet/airframe/blob/2c6461afe5eb6333f8ac0a2eed2f832c63803ee9/airframe/.jvm/src/main/scala/wvlet/airframe/lifecycle/AddShutdownHook.scala#L42, which closes logger when all sessions are terminated.

**Comment by xerial** [comment]
If we don't call resetFinally explicitly, AiframeLogManager will remain in the same class loader with java.util.logging and it will cause ClassNotFoundError at sbt's layered class loader because java.util.logigng is loaded at an upper layer of classloader (not an application-level class loader). 

If we remove AirframeLogManager, all log messages while shutting down jvm will not be shown.

**Comment by xerial** [comment]
Anyway, resetting the logger when all session is closed is not the right timing. We need to have a workaround.

**Comment by xerial** [comment]
I tested #1070 locally, and it seems the latest sbt might have solved this issue (no ClassNotFound error is shown). So I removed the logger unregistration code.

**Comment by takezoe** [comment]
Thanks!!
