### ISSUE TITLE
Add AirSpec to sbt

### ISSUE THREAD

**Issue by xerial** [wvlet/airframe#1680]
If sbt supports AirSpec, we don't need to explicitly set TestFramework. 
An example https://github.com/sbt/sbt/commit/fad8e8c3c9aebcc72363ef709e933b422af4514e

**Comment by xerial** [comment]
Created a PR https://github.com/sbt/sbt/pull/6513

**Comment by exoego** [comment]
Closing as wontfix since https://github.com/sbt/sbt/pull/6513 was rejected.
We may when "Used by" reaches 100 (right now 32, [most of them are Aiframe internal](https://mvnrepository.com/artifact/org.wvlet.airframe/airspec/usages)).

<img width="614" alt="image" src="https://user-images.githubusercontent.com/127635/208225932-e79a3ce5-2102-4163-8058-0341756e0307.png">
