### ISSUE TITLE
airframe-msgpack: why is there only LongValue and no IntValue

### ISSUE THREAD

**Issue by Sciss** [wvlet/airframe#1774]
hi there. implementing the neovim API, it has lots of 32-bit integers. why is there no dedicated `IntValue` sub-type of `IntegerValue`? Both decoder and encoder seem to require `LongValue` instead.

**Comment by xerial** [comment]
@Sciss It's because of the MessagePack type system specification https://github.com/msgpack/msgpack/blob/master/spec.md#type-system. 

Value objects are the representation of message pack values. If you need to read int32 without involving Long, low-level unpacker needs to be used.

**Comment by xerial** [comment]
Value objects has been defined for simplifying application development as the user only need to care about Nil, Integer (Long in Scala), Float (double), Boolean, Array, Map, String, etc.

**Comment by Sciss** [comment]
I see. It's just that I write `.toInt` literally everywhere. I think it makes sense to be able to match against 32-bit types, even if that is just an extractor.

**Comment by xerial** [comment]
There are several options we can use:
- unpackInt https://github.com/wvlet/airframe/blob/master/airframe-msgpack/src/main/scala/wvlet/airframe/msgpack/spi/Unpacker.scala#L45
- asInt https://github.com/wvlet/airframe/blob/master/airframe-msgpack/src/main/scala/wvlet/airframe/msgpack/spi/Value.scala#L95
- Use airframe-codec with a case class with Int parameters so that we don't need to manually decode MessagePack https://wvlet.org/airframe/docs/airframe-codec
