### ISSUE TITLE
A class defined by `toInstanceOf` to be singleton unexpectedly.

### ISSUE THREAD

**Issue by dotneet** [wvlet/airframe#2545]
In the document, `toInstanceOf` is explained as follows

```
Bind a class AImpl to A (Create a new instance each time)
```

But, in 22.11.0, `BbbImpl` in the following code example is called only once even though it's defined by `toInstanceOf` method. In 19.6.1, it is called twice.

Referring to the document, 22.11.0 seems to be buggy.

```scala
package com.example

import wvlet.airframe.newDesign

trait Bbb
class BbbImpl() extends Bbb {
  // this line expected to be called twice.
  println("created BbbImpl")
}

class Aaa1(bbb: Bbb) {
  println("created Aaa1")
}
class Aaa2(bbb: Bbb) {
  println("created Aaa2")
}

object Main {
  def main(args:Array[String]): Unit = {
    val rootDesign = newDesign
      .bind[Bbb].toInstanceOf[BbbImpl]

    val cs = rootDesign.newSession
    cs.build[Aaa1]
    cs.build[Aaa2]
  }
}
```

Output of 22.10.0
```
created BbbImpl
created Aaa1
created Aaa2
```

Output of 19.6.1
```
created BbbImpl
created Aaa1
created BbbImpl
created Aaa2
```

**Comment by xerial** [comment]
Creating new instances in DI has been deprecated mainly because of the complexity of the life cycle management of instances. For example, the DI session needs to remember all of the instances created to properly close all of them when the session terminates. So, for simplicity airframe will only create a singleton in future versions. These methods are already deprecated in Scala 3.

If you need to create a new instance every time, I recommend binding your factory class (e.g., BbbFactory, BbbFactory.createInstance(...)) instead.

To make this deprecation explicit, added deprecated annotation to these methods in #2566.

Thanks for reporting.
