### ISSUE TITLE
[Proposal] airframe-control: Implicit classes offering universal syntax sugar for Parallel

### ISSUE THREAD

**Issue by takezoe** [wvlet/airframe#425]
The current code which uses `Parallel` is:

```scala
import wvlet.airframe.control.Parallel

// for Seq
val result = Parallel.run(source, parallelism = 3) { i =>
  ...
}

// for Iterator
val result = Parallel.iterate(source, parallelism = 3) { i =>
  ...
}
```

My idea is adding implicit classes allowing above code to rewrite as follows:

```scala
import wvlet.airframe.control.Parallel.implicits._

// for Seq and Iterator
val result = source.parallelMap(parallelism = 3) { i =>
  ...
}
```

How do you think about this idea?

**Comment by xerial** [comment]
I prefer using the base package object `import wvlet.airframe.control.parallel._` if this is for user convenience. 

For now adding this syntax sugar with implicit class is OK, because we don't need to chain parallel methods. If we need to support more concatenated operations that is sharing the same thread pool, we may need to introduce free-monad like operators (e.g., Parallel(seq).map(x => ...) ) to embed the execution context like thread pools.  

Additional ideas:
- In future, I'd like to add similar options with GNU parallel (e.g., non-order preserving output, pipe (merging stdio, etc.), task queue size). 
- Seq[X] can be Iterate or TraversableOnce, so switching Parallel.run or Parallel.iterate will not work as you might expect. I think we should add mapParallel and mapParallelIterate. This reminds me `Stream[X]` abstraction, which will be deprecated in Scala 2.13 because of its confusing interface with Seq.

**Comment by takezoe** [comment]
Basic syntax sugar has been implemented in #429 as:

```scala
Seq(1, 2, 3).parallel.map(x => ...)
Seq(1, 2, 3).parallel.withParallelism(4).map(x => ...)
```

I'll keep working on other improvements for Parallel. I would like to make possible to share same thread pool (`ExecutorService` or `ExecutionContext`?) among concatenated map processes at least.

**Comment by takezoe** [comment]
I tried to implement some patterns sharing `ExecutionContext` across multiple map processes but I was not able to find a better solution than Scala's standard `Future`. In fact, it became very similar to `Future` because `Future` already has filled our requirements.

**Comment by xerial** [comment]
Now that #429 is merged, let me close this.
